Use versionless features
OpenLiberty/guide-microprofile-istio-retry-fallback pull request #175
Opened 2024-11-13 22:08 UTC by gkwan-ibm

address issue: https://github.com/OpenLiberty/guides-common/issues/1068

2025-01-31 19:21 UTC, shin19991207 approved these changes

2025-02-05 15:05 UTC, dmuelle requested changes
ID review - avoid using "above" "below" because they violate a11y standards. I'm not sure what to recommend for line 559 because Im not sure of the intended meaning

2025-02-05 15:05 UTC, dmuelle commented on README.adoc
> +The above command returns 5, because there was a total of 5 requests made to the `system` service that included the initial request, 3 MicroProfile retry requests, and the succesful request that you
```suggestion
This command returns 5 because you made a total of 5 requests to the `system` service: the initial request, 3 MicroProfile retry requests, and the successful request that you made before you paused the `system` service.
```

2025-02-05 15:05 UTC, dmuelle commented on README.adoc
> +The above command returns a value of 20, indicating that a total of 20 requests are made to the `system` service that are multiplied by the following:
Im not sure what is meant by " a total of 20 requests are made to the `system` service that are multiplied by the following:"

does it mean 5 Istio requests x 4 MP requests = 20?
or 20 x 4 x 5 = 400?

2025-02-05 15:05 UTC, dmuelle commented on README.adoc
> +The above command returns 5, indicating that a total of 5 requests are made to the `system` service.
```suggestion
This command returns 5, indicating that a total of 5 requests were made to the `system` service.
```

2025-02-05 15:05 UTC, dmuelle commented on README.adoc
> +The above command returns 1, indicating that totally 1 request is made to the `system` service.
```suggestion
This command returns 1, indicating that 1 request was made to the `system` service.
```

2025-02-05 15:05 UTC, dmuelle commented on README.adoc
> +Although the [hotspot=getPropertiesForHost file=1]`getPropertiesForHost()` method failed, the [hotspot=fallbackMethod file=1]`getPropertiesFallback()` fallback method is called.
```suggestion
Although the [hotspot=getPropertiesForHost file=1]`getPropertiesForHost()` method failed, the [hotspot=fallbackMethod file=1]`getPropertiesFallback()` fallback method was called.
```

2025-02-05 15:18 UTC, gkwan-ibm commented on README.adoc
> +The above command returns a value of 20, indicating that a total of 20 requests are made to the `system` service that are multiplied by the following:
it means -> 5 Istio requests x 4 MP requests = 20

2025-02-05 15:52 UTC, dmuelle commented on README.adoc
> +The above command returns a value of 20, indicating that a total of 20 requests are made to the `system` service that are multiplied by the following:
```suggestion
This command returns a value of 20, indicating that a total of 20 requests were made to the `system` service, including:
```

2025-02-05 15:53 UTC, dmuelle commented on README.adoc
> +* 5 Istio requests that included the initial request and 4 retry requests that you enabled in the [hotspot=attempts file=0]`traffic.yaml` file
```suggestion
* 5 Istio requests: the initial request and 4 retry requests that you enabled in the [hotspot=attempts file=0]`traffic.yaml` file
```

2025-02-05 15:54 UTC, dmuelle commented on README.adoc
> +* 4 requests sent by MicroProfile that included the initial request and [hotspot=mpRetry file=1]`3` retry requests
```suggestion
* For each of the 5 Istio requests, MicroProfile sent 4 requests:  the initial request and [hotspot=mpRetry file=1]`3` retry requests
```

2025-02-05 17:05 UTC, dmuelle approved these changes
LGTM- thanks

2025-02-05 22:10 UTC, merged