using istioctl
OpenLiberty/guide-microprofile-istio-retry-fallback pull request #62
Opened 2020-10-16 21:14 UTC by tt-le

Updated deploy istio section to use `istioctl` for installation and update tearing down section with `istioctl`.
Related to Issue:  @[OpenLiberty/guide-istio-intro](https://github.com/OpenLiberty/guide-istio-intro/issues/106)

2020-10-22 19:16 UTC, gkwan-ibm reviewed
@tt-le  at "Enabling MicroProfile Fault Tolerance" section
- change "Navigate to the `start` directory..." -> "Navigate to the `guide-{projectid}\start` directory..."

2020-10-29 20:09 UTC, gkwan-ibm requested changes

2020-10-29 20:09 UTC, gkwan-ibm commented on README.adoc
> +Navigate to the `guide-{projectid}\start` directory to begin.
@tt-le  change `guide-{projectid}\start` to `guide-{projectid}/start`

2020-10-29 20:09 UTC, gkwan-ibm commented on README.adoc
> +Navigate to the `guide-{projectid}\start` directory and run the following command to build your application and integrate the Retry policy into your microservices:
@tt-le change `guide-{projectid}\start` to `guide-{projectid}/start`

2020-11-02 22:08 UTC, tt-le commented
Addressed feedback. Changed the README to use the guides-commons adoc.

2020-11-03 17:23 UTC, gkwan-ibm approved these changes

2020-11-03 17:24 UTC, merged